setx1 = set(["green", "blue"])
setx2 = set(["blue", "yellow"])
print("Original sets:")
print(setx1)
print(setx2)
setc = setx1 | setx2 # union of two sets using |
print("\nUnion of sets:")
print(setc)
setn1 = set([1, 1, 2, 3, 4, 5])
setn2 = set([1, 5, 6, 7, 8, 9])
print("\nOriginal sets:")
print(setn1)
print(setn2)
print("\nUnion of sets:")
setn = setn1.union(setn2)
print(setn)
